### ISSUE TITLE
Ores from this mod are insusceptible to the fortune enchant

### ISSUE THREAD

**Issue by Greg-21** [Coliwogg/Gems-And-Crystals#10]
All ores from this mod are insusceptible to any level of the fortune enchant, so from one ore always drop one gem.

For comparison, in Gems and Crystals mod for Minecraft 1.15 and even the one for 1.14 the fortune enchant works correctly (I checked it out), so I hope you can simply backport some parts of the source code.

This issue has already been reported some time ago by user anakin_guy in the comments section of Gems and Crystals project page on CurseForge, but I have totally forgotten about it until this issue also happened to me :/

I was able to reproduce this issue on the following configuration (I didn't test other configs for Minecraft 1.12.2):
* Minecraft version: 1.12.2
* Gems and Crystals version: 1.2.7.2
* Forge versions: 14.23.5.2847

**Comment by Coliwogg** [comment]
This issue should be fixed in the new 1.2.7.3 version of the mod for Minecraft 1.12.2.
Thanks for letting me know of this issue!

**Comment by Greg-21** [comment]
@Coliwogg, thank you for all your work put into this mod. I really appreciate it.

**Comment by Greg-21** [comment]
Coliwogg, thank you for all your work put into this mod. I really appreciate it :)
