### ISSUE TITLE
Version 1.2.7 of this mod for Minecraft 1.12.2 crashes the game during startup

### ISSUE THREAD

**Issue by Greg-21** [Coliwogg/Gems-And-Crystals#8]
Version 1.2.7 (currently the newest one, marked as "stable" on CurseForge) of Gems and Crystals mod for Minecraft 1.12.2 crashes the game every time during startup, making it completely unplayable.

For comparison, version 1.1.3 (the previous one for Minecraft 1.12.2, marked as "beta" BTW) launches and works completely fine, however it has at least 2 irritating issues that I already reported on GitHub some time ago (I don't know whether they are still accessible or not, since you have removed that repository with them).

I was able to reproduce this issue on the following configurations (I didn't test other configs for Minecraft 1.12.2):
* Minecraft version: 1.12.2
* Gems and Crystals version: 1.2.7 for MC 1.12.2
* Forge versions: 14.23.5.2768, 14.23.5.2847, 14.23.5.2854

**Comment by Coliwogg** [comment]
This issue should be fixed in the 1.2.7.1 update of the mod for Minecraft 1.12.2.

**Comment by Greg-21** [comment]
Now everything seems to work properly again. Thank you for the fix.

**Comment by Greg-21** [comment]
Now everything seems to work properly again. Thank you for the fix.
